# Generated by Django 2.2.3 on 2019-07-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='redditapp.Text'),
        ),
    ]
