# Generated by Django 2.2.3 on 2019-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0002_auto_20190721_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
