# Generated by Django 2.2.3 on 2019-07-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0004_auto_20190719_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
