# Generated by Django 2.2.3 on 2019-07-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditapp', '0004_auto_20190722_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
